local mod = CoopEnhanced;

mod.Animations = {
	Active = "gfx/ui/items_coop.anm2", -- taken from coopHUD (Srokks), edited
	Banner = "gfx/ui/ui_streak.anm2",
	Book = "gfx/005.100_collectible.anm2",
	Chargebar = "gfx/ui/ui_chargebar.anm2",
	Coop = "gfx/ui/coop menu.anm2", 
	Crafting = "gfx/ui/ui_crafting.anm2",
	Fortune = "gfx/ui/ui_fortunepaper.anm2",
	Inventory = "gfx/ui/coopHUD_inventory.anm2", -- taken from coopHUD+ (Konoca)
	Item = "gfx/005.100_collectible.anm2",
	Misc = "gfx/ui/hudpickups.anm2",
	Pocket = "gfx/ui/coopHUD_cardspills.anm2", -- taken from coopHUD+ (Konoca)
	Poops = "gfx/ui/ui_poops.anm2",
	Stats = "gfx/ui/hudstats2.anm2",
	Trinket = "gfx/005.100_collectible.anm2",
	Waves = "gfx/ui/ui_wavebar.anm2",
};
mod.Images = {
	Blank = "gfx/ui/blank.png",
	BookOfBelial = "gfx/ui/hud_bookofbelial.png",
	BookOfVirtues = "gfx/ui/hud_bookofvirtues.png",
	BookOfBelialVirtues = "gfx/ui/hud_bookofvirtueswithbelial.png",
	CardsPills = "gfx/ui/ui_cardspills.png",
	CardFronts = "gfx/ui/ui_cardfronts.png",
	DInfinity = "gfx/characters/costumes/costume_489_dinfinity.png",
	EverythingJar = "gfx/ui/hud_everythingjar.png",
	Flip = "gfx/ui/hud_flip.png",
	GlowingHourGlass = "gfx/ui/hud_glowinghourglass.png",
	TheJar = "gfx/characters/costumes/costume_rebirth_90_thejar.png",
	JarOfFlies = "gfx/characters/costumes/costume_434_jarofflies.png",
	JarOfWisps = "gfx/ui/hud_jarofwisps.png",
	MamaMega = "gfx/ui/hud_mamamega.png",
	QuestionMark = "gfx/items/collectibles/questionmark.png",
	Smelter = "gfx/ui/hud_smelter.png",
	UrnOfSouls = "gfx/ui/hud_urnofsouls.png",
};
mod.Fnts = {
	upheaval = "font/upheaval.fnt",
	upheavalmini = "font/upheavalmini.fnt",
	terminus = "font/terminus.fnt",
	terminus8 = "font/terminus8.fnt",
	droid = "font/droid.fnt",
	luamini = "font/luamini.fnt",
	luaminioutlined = "font/luaminioutlined.fnt",
	pftempestasevencondensed = "font/pftempestasevencondensed.fnt",
	teammeatfont10 = "font/teammeatfont10.fnt",
	teammeatfont12 = "font/teammeatfont12.fnt",
	teammeatfont16 = "font/teammeatfont16.fnt",
	teammeatfont16bold = "font/teammeatfont16bold.fnt",
	teammeatfont20bold = "font/teammeatfont20bold.fnt",
};
mod.Colors = {
	{Name = "Alice Blue",Value = Color(0.8,0.8,1,1)},
	{Name = "Aqua",Value = Color(0,0.75,1,1)},
	{Name = "Aquamarine",Value = Color(0.5,1,0.8,1)},
	{Name = "Black",Value = Color(0.1,0.1,0.1,1)},
	{Name = "Blood",Value = Color(1,0.25,0.25,1)},
	{Name = "Blue",Value = Color(0,0,1,1)},
	{Name = "Brown",Value = Color(0.65,0.30,0.2,1)},
	{Name = "Dark Blue",Value = Color(0.1,0.1,0.45,1)},
	{Name = "Dark Green",Value = Color(0,0.5,0,1)},
	{Name = "Dark Orange",Value = Color(1,0.25,0,1)},
	{Name = "Dark Violet",Value = Color(0.6,0,0.8,1)},
	{Name = "Devil",Value = Color(0.55,0,0,1)},
	{Name = "Gold",Value = Color(1,0.85,0,1)},
	{Name = "Golden Rod",Value = Color(0.85,0.65,0.15,1)},
	{Name = "Grass",Value = Color(0.7,1,0.25,1)},
	{Name = "Gray",Value = Color(0.5,0.5,0.5,1)},
	{Name = "Green",Value = Color(0.2,0.8,0.2,1)},
	{Name = "Holy",Value = Color(0.95,0.9,0.55,1)},
	{Name = "Hot Pink",Value = Color(1,0.1,0.6,1)},
	{Name = "Lavender",Value = Color(0.85,0.7,0.85,1)},
	{Name = "Light Blue",Value = Color(0.5,0.8,0.9,1)},
	{Name = "Light Green",Value = Color(0.6,1,0.6,1)},
	{Name = "Light Pink",Value = Color(1,0.75,0.8,1)},
	{Name = "Light Purple",Value = Color(0.85,0.75,0.85,1)},
	{Name = "Light Red",Value = Color(0.95,0.5,0.5,1)},
	{Name = "Light Yellow",Value = Color(0.95,0.90,0.65,1)},
	{Name = "Lime",Value = Color(0,1,0,1)},
	{Name = "Olive",Value = Color(0.5,0.5,0,1)},
	{Name = "Orange",Value = Color(1,0.5,0,1)},
	{Name = "Pink",Value = Color(1,0.4,0.75,1)},
	{Name = "Poop",Value = Color(0.55,0.25,0.05,1)},
	{Name = "Purple",Value = Color(0.5,0,0.5,1)},
	{Name = "Red",Value = Color(1,0,0,1)},
	{Name = "Royal Blue",Value = Color(0.25,0.40,0.9,1)},
	{Name = "Sea Green",Value = Color(0.2,0.55,0.35,1)},
	{Name = "Silver",Value = Color(0.75,0.75,0.75,1)},
	{Name = "Slate",Value = Color(0.45,0.5,0.55,1)},
	{Name = "Soul",Value = Color(0.75,0.9,1.8,1)},
	{Name = "Steel Blue",Value = Color(0.25,0.5,0.7,1)},
	{Name = "Tan",Value = Color(0.8,0.7,0.55,1)},
	{Name = "Tomato",Value = Color(1,0.4,0.3,1)},
	{Name = "Violet",Value = Color(0.9,0.5,0.9,1)},
	{Name = "White",Value = Color(1,1,1,1)},
	{Name = "Yellow",Value = Color(1,1,0,1)},
};
mod.Characters = {
	{Name = "Issac", Type = PlayerType.PLAYER_ISAAC, Achievement = nil},
	{Name = "Magdalene", Type = PlayerType.PLAYER_MAGDALENE, Achievement = Achievement.MAGDALENE},
	{Name = "Cain", Type = PlayerType.PLAYER_CAIN, Achievement = Achievement.CAIN},
	{Name = "Judas", Type = PlayerType.PLAYER_JUDAS, Achievement = Achievement.JUDAS},
	{Name = "Dark Judas", Type = PlayerType.PLAYER_BLACKJUDAS, Achievement = Achievement.JUDAS},
	{Name = "???", Type = PlayerType.PLAYER_BLUEBABY, Achievement = Achievement.BLUE_BABY},
	{Name = "Eve", Type = PlayerType.PLAYER_EVE, Achievement = Achievement.EVE},
	{Name = "Samson", Type = PlayerType.PLAYER_SAMSON, Achievement = Achievement.SAMSON},
	{Name = "Azazel", Type = PlayerType.PLAYER_AZAZEL, Achievement = Achievement.AZAZEL},
	{Name = "Lazarus", Type = PlayerType.PLAYER_LAZARUS, Achievement = Achievement.LAZARUS},
	{Name = "Lazarus Risen", Type = PlayerType.PLAYER_LAZARUS2, Achievement = Achievement.LAZARUS, Sprite = {Frame = PlayerType.PLAYER_LAZARUS + 1}},
	{Name = "Eden", Type = PlayerType.PLAYER_EDEN, Achievement = Achievement.EDEN},
	{Name = "Lost", Type = PlayerType.PLAYER_THELOST, Achievement = Achievement.THE_LOST},
	{Name = "Lilith", Type = PlayerType.PLAYER_LILITH, Achievement = Achievement.LILITH},
	{Name = "Keeper", Type = PlayerType.PLAYER_KEEPER, Achievement = Achievement.KEEPER},
	{Name = "Apollyon", Type = PlayerType.PLAYER_APOLLYON, Achievement = Achievement.APOLLYON},
	{Name = "Forgotten", Type = PlayerType.PLAYER_THEFORGOTTEN, Achievement = Achievement.THE_FORGOTTEN},
	{Name = "Soul", Type = PlayerType.PLAYER_THESOUL, Achievement = Achievement.THE_FORGOTTEN, Sprite = {Frame = PlayerType.PLAYER_THEFORGOTTEN + 1}},
	{Name = "Bethany", Type = PlayerType.PLAYER_BETHANY, Achievement = Achievement.BETHANY},
	{Name = "Jacob", Type = PlayerType.PLAYER_JACOB, Achievement = Achievement.JACOB_AND_ESAU},
	{Name = "Esau", Type = PlayerType.PLAYER_ESAU, Achievement = Achievement.JACOB_AND_ESAU, Sprite = {Frame = PlayerType.PLAYER_JACOB + 1}},
	{Name = "The Broken", Type = PlayerType.PLAYER_ISAAC_B, Achievement = Achievement.TAINTED_ISAAC},
	{Name = "The Dauntless", Type = PlayerType.PLAYER_MAGDALENE_B, Achievement = Achievement.TAINTED_MAGDALENE},
	{Name = "The Hoarder", Type = PlayerType.PLAYER_CAIN_B, Achievement = Achievement.TAINTED_CAIN},
	{Name = "The Deceiver", Type = PlayerType.PLAYER_JUDAS_B, Achievement = Achievement.TAINTED_JUDAS},
	{Name = "The Soiled", Type = PlayerType.PLAYER_BLUEBABY_B, Achievement = Achievement.TAINTED_BLUE_BABY},
	{Name = "The Curdled", Type = PlayerType.PLAYER_EVE_B, Achievement = Achievement.TAINTED_EVE},
	{Name = "The Savage", Type = PlayerType.PLAYER_SAMSON_B, Achievement = Achievement.TAINTED_SAMSON},
	{Name = "The Benighted", Type = PlayerType.PLAYER_AZAZEL_B, Achievement = Achievement.TAINTED_AZAZEL},
	{Name = "The Enigma", Type = PlayerType.PLAYER_LAZARUS_B, Achievement = Achievement.TAINTED_LAZARUS},
	{Name = "amginE ehT", Type = PlayerType.PLAYER_LAZARUS2_B, Achievement = Achievement.TAINTED_LAZARUS, Sprite = {Frame = PlayerType.PLAYER_LAZARUS_B + 1}},
	{Name = "The Capricious", Type = PlayerType.PLAYER_EDEN_B, Achievement = Achievement.TAINTED_EDEN},
	{Name = "The Baleful", Type = PlayerType.PLAYER_THELOST_B, Achievement = Achievement.TAINTED_THE_LOST},
	{Name = "The Harlot", Type = PlayerType.PLAYER_LILITH_B, Achievement = Achievement.TAINTED_LILITH},
	{Name = "The Miser", Type = PlayerType.PLAYER_KEEPER_B, Achievement = Achievement.TAINTED_KEEPER},
	{Name = "The Empty", Type = PlayerType.PLAYER_APOLLYON_B, Achievement = Achievement.TAINTED_APOLLYON},
	{Name = "The Fettered", Type = PlayerType.PLAYER_THESOUL_B, Achievement = Achievement.TAINTED_THE_FORGOTTEN, Sprite = {Frame = PlayerType.PLAYER_THEFORGOTTEN_B + 1}},
	{Name = "Dead Weight", Type = PlayerType.PLAYER_THEFORGOTTEN_B, Achievement = Achievement.TAINTED_THE_FORGOTTEN},
	{Name = "The Zealot", Type = PlayerType.PLAYER_BETHANY_B, Achievement = Achievement.TAINTED_BETHANY},
	{Name = "The Deserter", Type = PlayerType.PLAYER_JACOB_B, Achievement = Achievement.TAINTED_JACOB_AND_ESAU},
	{Name = "Revenant", Type = PlayerType.PLAYER_JACOB2_B, Achievement = Achievement.TAINTED_JACOB_AND_ESAU, Sprite = {Frame = PlayerType.PLAYER_JACOB_B + 1}},
};
mod.CharactersModded = {};
mod.PocketSlot = {
	PERMA = 1,
	SINGLE = 2,
};
mod.TrinketSlot = {
	PRIMARY = 0,
	SECONDARY = 1,
};
mod.HealthTypes = {
	[1] = {Name = "Empty Heart", Total = 2},
	[2] = {Name = "Red Heart", Total = 2},
	[3] = {Name = "Soul Heart", Total = 2},
	[4] = {Name = "Black Heart", Total = 2},
	[5] = {Name = "Bone Heart", Total = 1},
	[6] = {Name = "Rotten Heart", Total = 1},
	[7] = {Name = "Eternal Heart", Total = 1},
	[8] = {Name = "Gold Heart", Total = 1},
	[9] = {Name = "Broken Heart", Total = 1},
};
mod.StageTypes = {
	["Special"] = 0,
	["Basement"] = 1,
	["Cellar"] = 2,
	["Burning Basement"] = 3,
	["Caves"] = 4,
	["Catacombs"] = 5,
	["Flooded Caves"] = 6,
	["Depths"] = 7,
	["Necropolis"] = 8,
	["Dank Depths"] = 9,
	["Womb"] = 10,
	["Utero"] = 11,
	["Scarred Womb"] = 12,
	["Blue Womb"] = 13,
	["Sheol"] = 14,
	["Cathedral"] = 15,
	["Dark Room"] = 16,
	["Chest"] = 17,
	["Greed Special Rooms"] = 18,
	["Greed Basement"] = 19,
	["Greed Caves"] = 20,
	["Greed Depths"] = 21,
	["Greed Womb"] = 22,
	["Greed Sheol"] = 23,
	["The Shop"] = 24,
	["Ultra Greed"] = 25,
	["The Void"] = 26,
	["Downpour"] = 27,
	["Dross"] = 28,
	["Mines"] = 29,
	["Ashpit"] = 30,
	["Mausoleum"] = 31,
	["Gehenna"] = 32,
	["Corpse"] = 33,
	["Home"] = 35,
	["Backwards"] = 36
};
mod.Priorities = {
	CallbackPriority.IMPORTANT,
	CallbackPriority.EARLY,
	CallbackPriority.DEFAULT,
	CallbackPriority.LATE, 
	200
};
mod.Controls = {
	{Name = "Drop + Map", Buttons = Vector(ButtonAction.ACTION_DROP,ButtonAction.ACTION_MAP), Held = false},
	{Name = "Hold Map 3s", Buttons = Vector(ButtonAction.ACTION_MAP,180), Held = true},
};
mod.GridSize = 40;